<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>4f8fb0bf-1d34-446a-abad-adc20e1551c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.sc-fAjcbJ.wtnFq.buttonStyle.ant-btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e157308-3316-4274-aba3-9d7af9d0bc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rtl</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>6a460484-9206-46a0-9674-b5dd7ebc17d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a05900f-3412-42a6-abe0-f251d1d12729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn sc-fAjcbJ wtnFq buttonStyle ant-btn-primary</value>
      <webElementGuid>9922ed3d-d9ef-42b3-b271-023a9f036db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>1776828a-eb9a-481e-949f-581fc7303498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;career-main-container&quot;)/main[@class=&quot;isomorphicContent ant-layout-content&quot;]/div[1]/div[@class=&quot;sc-kAzzGY idHZcR isoLayoutContentWrapper&quot;]/div[@class=&quot;sc-chPdSV eAblcU&quot;]/div[@class=&quot;sc-fBuWsC cyWUiq&quot;]/div[@class=&quot;sc-eqIVtm iylmTi&quot;]/div[@class=&quot;textPosition textStyle&quot;]/div[@class=&quot;sc-kjoXOD dIsmxq&quot;]/div[@class=&quot;formContent&quot;]/button[@class=&quot;ant-btn sc-fAjcbJ wtnFq buttonStyle ant-btn-primary&quot;]</value>
      <webElementGuid>0a52210e-5ce7-41d1-bf77-75ccaab204db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>93bc7241-99e9-49f2-b456-e31dac21994a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='career-main-container']/main/div/div/div/div/div/div[5]/div/div[7]/button</value>
      <webElementGuid>7c682bc9-7583-4f24-969d-fb480bd7bf97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Sandi'])[1]/following::button[1]</value>
      <webElementGuid>3cc445e1-d5c1-4f70-8520-7c6c34be94e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingat Saya'])[1]/following::button[1]</value>
      <webElementGuid>350e2b7e-e0bf-4bb8-b538-a6138109f112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::button[1]</value>
      <webElementGuid>1d3a6313-e35c-4231-a811-9f6fdc80357f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button</value>
      <webElementGuid>4f602ac8-089c-47d9-b7ed-b84133edbff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>e2738cee-c7cb-42c6-bbe0-c4dd42cc4fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
