<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_reCAPTCHA_recaptcha-checkbox-border</name>
   <tag></tag>
   <elementGuidId>e13c253f-b912-4c4a-b501-1c3341ecc52c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.recaptcha-checkbox-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='recaptcha-anchor']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>463984bc-966b-468d-907a-5bbf5942d285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recaptcha-checkbox-border</value>
      <webElementGuid>068c9525-a862-4dc5-9415-3782558accda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2c188ba0-24a1-491f-9881-3f85e7c0f8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor&quot;)/div[@class=&quot;recaptcha-checkbox-border&quot;]</value>
      <webElementGuid>43221923-2cd9-4e05-ae3f-f771141b81cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/logincoba2/Page_Astra Career - Masuk/iframe_Lupa Sandi_a-nzavr6c81s52_1</value>
      <webElementGuid>6fe1881d-5bc7-4987-9e79-bfead6d496b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='recaptcha-anchor']/div</value>
      <webElementGuid>83d97817-8ef3-440c-a06e-d29e1ad41bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>9b896a0c-6edc-4fcf-ba51-d280239ad254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
