<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Sandi_a-nzavr6c81s52</name>
   <tag></tag>
   <elementGuidId>b8a273bc-1ad8-4150-8000-af394141c1a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-nzavr6c81s52&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-nzavr6c81s52']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c89d51b0-5322-411e-9fef-f806d44c8a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>880749a1-0427-4d38-bf1f-48a340ead893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfSxcUUAAAAABkKXCM--goHYUYBuGeLNqTepV0Y&amp;co=aHR0cHM6Ly9jYXJlZXIuYXN0cmEuY28uaWQ6NDQz&amp;hl=ID&amp;type=image&amp;v=8G7OPK94bhCRbT0VqyEVpQNj&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=py84as9lyjzx</value>
      <webElementGuid>cf79787a-d0d6-476e-9dfc-14a9e8616673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>b0490fc6-d854-4c57-b3ec-e7af9aa519bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>8118a916-1655-4b5b-b982-455accb8394b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2b7545a1-ba63-49cd-ab7e-1f700cc86e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-nzavr6c81s52</value>
      <webElementGuid>3b140e85-f32b-4cb4-9f8a-17a4842263a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17922492-9cbd-400e-bc41-48343bb358ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>78292d02-420c-4fdc-a981-f1c2992e8d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>7be16756-d8a0-44c4-95f6-c8e116ce0b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;career-main-container&quot;)/main[@class=&quot;isomorphicContent ant-layout-content&quot;]/div[1]/div[@class=&quot;sc-kAzzGY idHZcR isoLayoutContentWrapper&quot;]/div[@class=&quot;sc-chPdSV eAblcU&quot;]/div[@class=&quot;sc-fBuWsC cyWUiq&quot;]/div[@class=&quot;sc-eqIVtm iylmTi&quot;]/div[@class=&quot;textPosition textStyle&quot;]/div[@class=&quot;sc-kjoXOD dIsmxq&quot;]/div[@class=&quot;recaptchaBox&quot;]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>8458ef9b-abbe-4cd0-a632-994c47a4beb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-nzavr6c81s52']</value>
      <webElementGuid>4e4f7108-9bda-4810-8645-7c46c9693495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='career-main-container']/main/div/div/div/div/div/div[5]/div/div[6]/div/div/div/iframe</value>
      <webElementGuid>bd6efc9e-3f41-4d3f-81fc-066a9c8099c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2207250a-3500-46a9-95d6-12e3f91242f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfSxcUUAAAAABkKXCM--goHYUYBuGeLNqTepV0Y&amp;co=aHR0cHM6Ly9jYXJlZXIuYXN0cmEuY28uaWQ6NDQz&amp;hl=ID&amp;type=image&amp;v=8G7OPK94bhCRbT0VqyEVpQNj&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=py84as9lyjzx' and @name = 'a-nzavr6c81s52']</value>
      <webElementGuid>88b614dd-6946-40cf-9800-6986584fd36f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
