<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Sandi_a-nzavr6c81s52_1</name>
   <tag></tag>
   <elementGuidId>6b7404df-c582-44d8-a812-3d6a14a6ce4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-nzavr6c81s52&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-nzavr6c81s52']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3ce25b7c-2423-4282-b21b-698f514047fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>14f2863f-d0f9-4959-8cf2-ead270696ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfSxcUUAAAAABkKXCM--goHYUYBuGeLNqTepV0Y&amp;co=aHR0cHM6Ly9jYXJlZXIuYXN0cmEuY28uaWQ6NDQz&amp;hl=ID&amp;type=image&amp;v=8G7OPK94bhCRbT0VqyEVpQNj&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=t155bn6g89ey</value>
      <webElementGuid>5df8b97d-cc98-490f-88b6-ccb49faf870e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>435f1ac9-5d6c-45dd-86f4-1efe5a547846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>2657b105-5f22-48e8-a758-bfbe57447e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2ec26f05-181d-4a9c-b60a-cde47a4e6713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-nzavr6c81s52</value>
      <webElementGuid>f8f1da34-de5b-4608-bd69-67ddd2db3148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e73e41d9-177d-4a94-b46e-3a3089558e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>069beadc-a6e2-4ced-b819-ed9f1d1d32c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>134bc880-9dfa-4bab-b8e2-ea3f5aa19410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;career-main-container&quot;)/main[@class=&quot;isomorphicContent ant-layout-content&quot;]/div[1]/div[@class=&quot;sc-kAzzGY idHZcR isoLayoutContentWrapper&quot;]/div[@class=&quot;sc-chPdSV eAblcU&quot;]/div[@class=&quot;sc-fBuWsC cyWUiq&quot;]/div[@class=&quot;sc-eqIVtm iylmTi&quot;]/div[@class=&quot;textPosition textStyle&quot;]/div[@class=&quot;sc-kjoXOD dIsmxq&quot;]/div[@class=&quot;recaptchaBox&quot;]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>7aea4636-e0ca-43b2-bee0-4b26b4d49ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-nzavr6c81s52']</value>
      <webElementGuid>0d454d81-4f1d-497c-bf3e-9e89612176c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='career-main-container']/main/div/div/div/div/div/div[5]/div/div[6]/div/div/div/iframe</value>
      <webElementGuid>2ef1eba6-f720-4e7e-92a0-e52f0b311784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cd4d7945-ee22-49cf-946d-81714d7dba56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfSxcUUAAAAABkKXCM--goHYUYBuGeLNqTepV0Y&amp;co=aHR0cHM6Ly9jYXJlZXIuYXN0cmEuY28uaWQ6NDQz&amp;hl=ID&amp;type=image&amp;v=8G7OPK94bhCRbT0VqyEVpQNj&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=t155bn6g89ey' and @name = 'a-nzavr6c81s52']</value>
      <webElementGuid>a271129a-f142-40ef-805c-0bb0913fe1d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
