<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk_email</name>
   <tag></tag>
   <elementGuidId>2cb29553-2452-4d44-a8b7-116321fb3ddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52cef311-b029-4859-b2a4-11c1624dac32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15254a0c-fe6c-4d93-befa-8d3514e30d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input</value>
      <webElementGuid>3fc76522-6328-4c9d-a480-3d54b3e96d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E-mail</value>
      <webElementGuid>bc88253d-6ecb-4684-944f-bed82e98bf78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>6e3d6873-2ebc-41c8-804f-28a22aec4295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;career-main-container&quot;)/main[@class=&quot;isomorphicContent ant-layout-content&quot;]/div[1]/div[@class=&quot;sc-kAzzGY idHZcR isoLayoutContentWrapper&quot;]/div[@class=&quot;sc-chPdSV eAblcU&quot;]/div[@class=&quot;sc-fBuWsC cyWUiq&quot;]/div[@class=&quot;sc-eqIVtm iylmTi&quot;]/div[@class=&quot;textPosition textStyle&quot;]/div[@class=&quot;sc-kjoXOD dIsmxq&quot;]/div[@class=&quot;formContent&quot;]/input[@class=&quot;form-input&quot;]</value>
      <webElementGuid>b97501a8-6646-4879-897a-7ab4e51daeeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>e120e017-77b9-4491-b7fc-2f440e4ebceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='career-main-container']/main/div/div/div/div/div/div[5]/div/div[3]/input</value>
      <webElementGuid>5c716ca4-29c5-4a1c-8fef-49ea7f1c16d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>25d791b1-3272-4b66-9275-b885b49dc8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'E-mail' and @name = 'email']</value>
      <webElementGuid>82d38156-f166-405a-b4d1-5df346753dda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
